### ISSUE TITLE
Triggering preset generates warning ('NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by pjmaenh** [pjmaenh/home-assistant-vaillant#3]
When triggering a preset or switching system mode, a warning is generated (update for thermostat fails). 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vaillant/climate.py", line 206, in update
    self._data.update(no_throttle=True)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/vaillant/climate.py", line 224, in update
    self.thermostatdata = pyvaillant.VaillantThermostatData(self.auth)
  File "/usr/local/lib/python3.7/site-packages/smart_home/VaillantThermostat.py", line 26, in __init__
    self.update()                       # Get latest data
  File "/usr/local/lib/python3.7/site-packages/smart_home/VaillantThermostat.py", line 62, in update
    if 'setpoint_hwb' in self.devList[0] and self.devList[0]['setpoint_hwb']['setpoint_activate']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pjmaenh** [comment]
This warning can be safely ignored, and is the result of the API retiring an incomplete result.
